### ISSUE TITLE
Crashing on successful login.

### ISSUE THREAD

**Issue by Adictya** [GDGVIT/gidget#24]
**Describe the bug**
It crashes for me when I try to log in.

**To Reproduce**
1. Launch the app
2. Press login
3. Complete the login
4. Crash when focusing back on the app

**Expected behavior**
A successful login

**Environment**
DEVICE - Sam S9+, Android - 10

**Additional context**
Logcat -
```
2021-07-01 13:46:09.158 986-1902/? I/ClientCertificateManager Service: AdminId - 1250 UserId - 0 packageName - com.dscvit.gidget
2021-07-01 13:46:09.159 986-1902/? I/ClientCertificateManager Service: AdminId - 10033 UserId - 0 packageName - com.dscvit.gidget
2021-07-01 13:46:09.160 986-1902/? I/ClientCertificateManager Service: AdminId - 10216 UserId - 0 packageName - com.dscvit.gidget
2021-07-01 13:46:09.160 986-1902/? I/ClientCertificateManager Service: AdminId - 10614 UserId - 0 packageName - com.dscvit.gidget
2021-07-01 13:46:09.807 10039-10039/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.dscvit.gidget, PID: 10039
    java.lang.NullPointerException
        at com.dscvit.gidget.activities.MainActivity$onResume$1$onResponse$1.onResponse(MainActivity.kt:78)
        at retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall$1.lambda$onResponse$0$DefaultCallAdapterFactory$ExecutorCallbackCall$1(DefaultCallAdapterFactory.java:89)
        at retrofit2.-$$Lambda$DefaultCallAdapterFactory$ExecutorCallbackCall$1$hVGjmafRi6VitDIrPNdoFizVAdk.run(Unknown Source:6)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:8167)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
2021-07-01 13:46:09.824 986-1902/? W/ActivityManager: crash : com.dscvit.gidget,0
2021-07-01 13:46:09.834 986-1902/? W/ActivityTaskManager:   Force finishing activity com.dscvit.gidget/.activities.MainActivity
2021-07-01 13:46:09.881 986-1058/? I/WindowManager: Focus moving from Window{36dfb8 u0 com.dscvit.gidget/com.dscvit.gidget.activities.MainActivity} to null displayId=0
```

#### Is this is a critical security vulnerability?
- [ ] Yes: Please read code-of-conduct once
- [x] No

**Comment by SaurusXI** [comment]
@rishavnaskar check this, try to resolve asap

**Comment by rishavnaskar** [comment]
> **Describe the bug**
> It crashes for me when I try to log in.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Launch the app
> 2. Press login
> 3. Complete the login
> 4. Crash when focusing back on the app
> 
> **Expected behavior**
> A successful login
> 
> **Environment**
> DEVICE - Sam S9+, Android - 10
> 
> **Additional context**
> Logcat -
> 
> ```
> 2021-07-01 13:46:09.158 986-1902/? I/ClientCertificateManager Service: AdminId - 1250 UserId - 0 packageName - com.dscvit.gidget
> 2021-07-01 13:46:09.159 986-1902/? I/ClientCertificateManager Service: AdminId - 10033 UserId - 0 packageName - com.dscvit.gidget
> 2021-07-01 13:46:09.160 986-1902/? I/ClientCertificateManager Service: AdminId - 10216 UserId - 0 packageName - com.dscvit.gidget
> 2021-07-01 13:46:09.160 986-1902/? I/ClientCertificateManager Service: AdminId - 10614 UserId - 0 packageName - com.dscvit.gidget
> 2021-07-01 13:46:09.807 10039-10039/? E/AndroidRuntime: FATAL EXCEPTION: main
>     Process: com.dscvit.gidget, PID: 10039
>     java.lang.NullPointerException
>         at com.dscvit.gidget.activities.MainActivity$onResume$1$onResponse$1.onResponse(MainActivity.kt:78)
>         at retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall$1.lambda$onResponse$0$DefaultCallAdapterFactory$ExecutorCallbackCall$1(DefaultCallAdapterFactory.java:89)
>         at retrofit2.-$$Lambda$DefaultCallAdapterFactory$ExecutorCallbackCall$1$hVGjmafRi6VitDIrPNdoFizVAdk.run(Unknown Source:6)
>         at android.os.Handler.handleCallback(Handler.java:883)
>         at android.os.Handler.dispatchMessage(Handler.java:100)
>         at android.os.Looper.loop(Looper.java:237)
>         at android.app.ActivityThread.main(ActivityThread.java:8167)
>         at java.lang.reflect.Method.invoke(Native Method)
>         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
> 2021-07-01 13:46:09.824 986-1902/? W/ActivityManager: crash : com.dscvit.gidget,0
> 2021-07-01 13:46:09.834 986-1902/? W/ActivityTaskManager:   Force finishing activity com.dscvit.gidget/.activities.MainActivity
> 2021-07-01 13:46:09.881 986-1058/? I/WindowManager: Focus moving from Window{36dfb8 u0 com.dscvit.gidget/com.dscvit.gidget.activities.MainActivity} to null displayId=0
> ```
> 
> #### Is this is a critical security vulnerability?
> * [ ]  Yes: Please read code-of-conduct once
> * [x]  No

I will update the readme right now. I missed 2 steps

Basically, perform the following steps.

1. Create a Github personal access token with user and repo as scope.
2. Create a GitHub OAuth app. You will get a clientID and clientSecret.

Add the Personal Access Token as "token", ClientID as "clientID" and ClientSecret as "clientSecret" to your "System Variables" under "Environment Variables" in your pc. 
Then restart your pc and run the project.

My apologies for missing out this.

**Comment by rishavnaskar** [comment]
@Adictya bug has been fixed.

**Comment by rishavnaskar** [comment]
It happens if someone doesn't have a name in GitHub or has chosen to hide it. 

Anyway, @Siddhartha#3810 told to allow users with no name. So i will update the app now
